version: 1.0
provider:
  name: openfaas
  gateway: http://192.168.1.129:8080
functions:
  nodefunc:
    lang: node16
    handler: ./nodefunc
    image: ghcr.io/${OWNER:-spavett}/nodefunc:${TAG:-latest}

